# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  my_job:
    docker:
      - image: circleci/node:13.8.0   
    steps:
      - run: return 1
    when: on_fail
workflows:
  my_workflow:  # Define a Workflow 
    # Run the my_job job in its own container
    jobs:
      - my_job